version: '3.8'

services:
  ragflow:
    image: infiniflow/ragflow:latest
    ports:
      - "9380:9380"
    environment:
      - SECRET_KEY=${SECRET_KEY:-default-secret-key}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
